### ISSUE TITLE
TypeError: babel.Transformer is not a function

### ISSUE THREAD

**Issue by Koleok** [gavriguy/babel-plugin-project-relative-require#2]
@gavriguy First of all thanks for going the extra mile and making this solution available as a plugin.

I am getting something like :

```
...
/node_modules/babel-plugin-project-relative-require/index.js:8
  return new babel.Transformer("babel-plugin-project-relative-require", {
         ^

TypeError: babel.Transformer is not a function
...
```

after installing this, adding to `.babelrc` and my `webpack.config.js` _(maybe redundant to do both)_ and trying to use with the `cwd://` import sytax.

**Comment by gavriguy** [comment]
hi,
what babal version are you using?

**Comment by steve-gray** [comment]
Same here: babel-core 6.8.0.

-Steve

**Comment by gavriguy** [comment]
This plugin only supports babel 5.0 I'll update the doc.
Please note that I'm now using https://github.com/jshanson7/babel-plugin-resolver instead
